name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v7   

      - name: Remove unused packages
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/swift            
      
      - name: Free disk space
        run: |
          df -h       
      
      - name: Install uv
        uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies for Python  ${{ matrix.python-version }}
        run: uv sync --python ${{ matrix.python-version }} --group dev

      - name: Build Sphinx docs
        run: uv run sphinx-build -b html docs gh-pages

      - name: Run tests and generate coverage report
        run: |
          uv run coverage run -m pytest
          echo "COVERAGE=$(uv run coverage report --precision 2 | grep TOTAL | tr -s ' ' | cut -f 4 -d " ")" >> $GITHUB_ENV
          uv run coverage html --directory gh-pages/coverage
          rm -f gh-pages/coverage/.gitignore

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5


      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth:  ${{ secrets.GIST_SECRET }} 
          gistID: f1d9191993105301fd6f813fe1e659f6
          filename: coverage-badge.json
          label: coverage
          message:  ${{ env.COVERAGE }} 
          color: green

